services:
  postgres_database:
    image: postgres:latest
    container_name: book_station_database
    environment:
      POSTGRES_DB: book_station
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
volumes:
  db_test_volume:
    name: book_station_volume
